services:
    twig.exception_listener:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
            - 'Acme\JsonErrorBundle\Controller\ExceptionController::showAction'
            - @logger
        tags:
            - {name: kernel.event_subscriber}
            - {name: monolog.logger, channel: request}
